#!/bin/sh

#cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions

phycores=$(echo $sudoPW|cat - /proc/cpuinfo|grep -m 1 "cpu cores"|awk '{print $ 4;}')

echo "St. jeder na razpolago:" $phycores

read -p "Izberi stevilo jeder:" cN

lineNum="$(grep -n "cN" ./constants | head -n 1 | cut -d: -f1)" #doloci stevilko vrstice v kateri je cN

sed -i '/^$/d' ./constants #odstrani prazne vrstice

sed -i  "$lineNum"'d' ./constants #odstrani vrstico v kateri je cN

echo cN $cN\; >> ./constants # na konec file appenda cN

mkdir logs

surfaceCheck constant/triSurface/ailerons.stl | tee logs/surfaceCheck.ailerons.log
surfaceCheck constant/triSurface/fuselage.stl | tee logs/surfaceCheck.fuselage.log
surfaceCheck constant/triSurface/elevator.stl | tee logs/surfaceCheck.elevator.log


runApplication surfaceFeatureExtract

runApplication blockMesh

runApplication decomposePar

runParallel snappyHexMesh -overwrite

runParallel simpleFoam

runParallel checkMesh -allGeometry -allTopology -writeAllFields -writeSets vtk

runApplication reconstructParMesh

runApplication reconstructPar 

mydir="$(basename $PWD)"
echo "$mydir"
#
touch foam"$mydir".foam