#!/bin/sh

cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions

phycores=$(echo $sudoPW|cat - /proc/cpuinfo|grep -m 1 "cpu cores"|awk '{print $ 4;}')

echo "St. jeder na razpolago:" $phycores

read -p "Izberi stevilo jeder:" cN

lineNum="$(grep -n "cN" ./constants | head -n 1 | cut -d: -f1)" #doloci stevilko vrstice v kateri je cN

sed -i '/^$/d' ./constants #odstrani prazne vrstice

sed -i  "$lineNum"'d' ./constants #odstrani vrstico v kateri je cN

echo cN $cN\; >> ./constants # na konec file appenda cN

mkdir logs

surfaceCheck constant/triSurface/ailerons.stl | tee logs/surfaceCheck.ailerons.log
surfaceCheck constant/triSurface/fuselage.stl | tee logs/surfaceCheck.fuselage.log
surfaceCheck constant/triSurface/elevator.stl | tee logs/surfaceCheck.elevator.log


runApplication surfaceFeatureExtract | tee logs/surfaceFeatureExtract.log

runApplication blockMesh | tee logs/blockMesh.log

runApplication decomposePar | tee logs/decomposeParsHM.log

mpirun -np $cN snappyHexMesh -parallel | tee logs/snappyHexMesh.log

checkMesh -allGeometry -allTopology -writeAllFields -writeSets vtk | tee logs/checkMesh.log

reconstructParMesh | tee logs/reconstructParMesh.log

cp -r 0.orig/* 3/

decomposePar -force -latestTime | tee logs/decomposePar.log

mpirun -np $cN simpleFoam -parallel | tee logs/simpleFoam.log

reconstructPar | tee logs/reconstructPar.log

mydir="$(basename $PWD)"
echo "$mydir"

touch foam"$mydir".foam